image: node:latest

build:
  script:
    - cd status
    - npm install
    - npm run build
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" > /dev/null
    - unzip awscliv2.zip > /dev/null
    - ./aws/install > /dev/null
    - /usr/local/bin/aws s3 sync --acl=public-read build/ s3://catalysts-decentraland-io-contentbucket-a220319/

