image: decentraland/ci-node:12

build:
  script:
    - cd status && yarn install && PUBLIC_URL=https://catalysts.decentraland.io yarn build && cd ..
    - dcl-lock-sync
    - cd .ci && npm install && dcl-up website-catalysts
    - dcl-sync-release && cd ..
    - dcl-upload status/build
    - cd .ci && dcl-cache-invalidation

