image: node:latest

cache:
  paths:
    - status/node_modules/

build:
  script:
    - cd status
    - npm install
    - npm build
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - /usr/local/bin/aws s3 sync build/ s3://catalysts-decentraland-io-contentbucket-c4f33da/

