import { Entity } from '@dcl/schemas'
import { DatabaseClient } from '../../adapters/database'
import { DeploymentId } from '../../types'

export type DeploymentResult = Map<string, { before: DeploymentId | undefined; after: DELTA_POINTER_RESULT }>

export enum DELTA_POINTER_RESULT {
  SET = 'set',
  CLEARED = 'cleared'
}

export type IPointerManager = {
  /**
   * Commit a new entity, and return the 'before & after' generated by the deployment.
   *
   * @param database - DB client; pass the active transaction client when called inside a deploy tx
   * @param entity - the entity being deployed
   * @param overwrittenDeploymentIds - ids of previously existing deployments being overwritten by this deployment
   * @param isEntityOverwrittenByAnExistingDeployment - whether the current deployment is old and has already been overwritten by a newer one
   *
   * @returns A map keyed by pointer with `before` (the previous deployment id, if any) and `after` (`'set'` or `'cleared'`).
   */
  referenceEntityFromPointers(
    database: DatabaseClient,
    entity: Entity,
    overwrittenDeploymentIds: Set<number>,
    isEntityOverwrittenByAnExistingDeployment: boolean
  ): Promise<DeploymentResult>
}
