@startuml
header "Content Server"
artifact "content-server" as contentserver
artifact "catalyst-api-specs" as catalystapispecs
artifact "@dcl/catalyst-contracts" as catalystcontracts
artifact "@dcl/content-validator" as contentvalidator
artifact "@dcl/crypto" as crypto
artifact "@dcl/hashing" as hashing
artifact "@dcl/schemas" as schemas
artifact "@dcl/snapshots-fetcher" as snapshotsfetcher
artifact "@dcl/urn-resolver" as urnresolver
artifact "eth-connect" as ethconnect
artifact "@dcl/content-hash-tree" as contenthashtree
artifact "@dcl/catalyst-storage" as catalyststorage
artifact "dcl-catalyst-client" as catalystclient
artifact "dcl-catalyst-commons" as catalystcommons

contentserver --> catalystapispecs
contentserver --> catalystcontracts
contentserver --> contentvalidator
contentserver --> crypto
contentserver --> hashing
contentserver --> schemas
contentserver --> snapshotsfetcher
contentserver --> urnresolver
contentserver --> catalystclient
catalystclient --> catalystcommons
catalystcontracts --> ethconnect
contentvalidator --> contenthashtree
contentvalidator --> hashing
contentvalidator --> schemas
contentvalidator --> urnresolver
crypto --> schemas
crypto --> ethconnect
snapshotsfetcher --> catalyststorage
snapshotsfetcher --> hashing
snapshotsfetcher --> schemas

newpage
header "Lambdas Server"
artifact "lambdas-server" as lambdasserver
artifact "catalyst-api-specs" as catalystapispecs
artifact "@dcl/catalyst-contracts" as catalystcontracts
artifact "@dcl/crypto" as crypto
artifact "@dcl/schemas" as schemas
artifact "@dcl/urn-resolver" as urnresolver
artifact "eth-connect" as ethconnect
artifact "dcl-catalyst-client" as catalystclient
artifact "dcl-catalyst-commons" as catalystcommons

lambdasserver --> catalystapispecs
lambdasserver --> catalystcontracts
lambdasserver --> crypto
lambdasserver --> schemas
lambdasserver --> urnresolver
lambdasserver --> catalystclient
lambdasserver --> catalystcommons
catalystclient --> catalystcommons
catalystcontracts --> ethconnect
crypto --> schemas
crypto --> ethconnect

@enduml
