name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: 8BitJonny/gh-get-current-pr@1.4.0
        id: PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Verbose setting SHA when using Pull_Request event trigger to fix #16
          sha: ${{ github.event.pull_request.head.sha }}
          # Only return if PR is still open
          filterOutClosed: true
      - run: echo "The pr title is ${prTitle}"
        if: success() && steps.PR.outputs.numberr
        env:
          prNumber: ${{ steps.PR.outputs.number }}
          # JSON object with the full PR object
          prJSON: ${{ steps.PR.outputs.pr }}
          # Direct access to common PR properties
          prUrl: ${{ steps.PR.outputs.pr_url }}
          prTitle: ${{ steps.PR.outputs.pr_title }}
          prBody: ${{ steps.PR.outputs.pr_body }}
          prCreatedAt: ${{ steps.PR.outputs.pr_created_at }}
          prMergedAt: ${{ steps.PR.outputs.pr_merged_at }}
          prClosedAt: ${{ steps.PR.outputs.pr_closed_at }}
          prLabel: ${{ steps.PR.outputs.pr_labels }}
      - run: echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
      # - run: echo "::error file={name},line={line},endLine={endLine},title={title}::{message}" && exit 1
  pr-title-matches-convention:
    runs-on: ubuntu-latest
    steps:
      - uses: 8BitJonny/gh-get-current-pr@1.4.0
        id: PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ steps.PR.outputs.pr_title }}
          regex: 'chore: '
          flags: gm
        env:
          prTitle: ${{ steps.PR.outputs.pr_title }}
      - run: echo "${{ steps.regex-match.outputs.match }}"
      - run: echo "::error file={name},line={line},endLine={endLine},title={title}::PR's title does not match the convention" && exit 1
        if: ${{ steps.regex-match.outputs.match != '' }}
